global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'collector-service'
    static_configs: 
      - targets: ['collector-service:8080']
  - job_name: 'cache-service'
    static_configs: 
      - targets: ['cache-service:9091']  
  - job_name: 'analytics-service'
    static_configs: 
      - targets: ['analytics-service:9093']
  