env: "dev"

server:
  port: "8081"
  timeout: 4s
  idle_timeout: 30s

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

broker:
  type: "kafka"
  kafka:
    brokers:  
      - "kafka:9092"
    topic: "metrics"
    group_id: "cache-group"

grpc:
  port: "50051"