env: "dev"

server:
  port: "9096"
  timeout: 4s
  idle_timeout: 30s

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

broker:
  type: "kafka"
  kafka:
    brokers:  
      - "kafka:9092"
    topic: "metrics"
    group_id: "notifier-group"

email:
  smtphost: ""
  smtpport: ""
  from: ""
  username: ""
  password: ""
  to: ""
